# Use the official Python image as the base image
FROM python:3.8-slim

# Set the working directory
WORKDIR /app

# Copy the Python script into the container
COPY app.py .

# Execute the Python script when the container runs
CMD ["python", "app.py"]